#pragma once
#include <HyperstreamRemixer/Macros/coerce-inline.h++>
#define REMIXER_VISUAL_DEBUGGER_SIGNATURE_SKELETON() __REMIXER_COERCE_INLINE void $describe_visual_debugger_imgui_frame()
#define REMIXER_VISUAL_DEBUGGER_FUNCTION_DEFINITION() static REMIXER_VISUAL_DEBUGGER_SIGNATURE_SKELETON()
#define REMIXER_VISUAL_DEBUGGER_FRIEND_DEFINITION() friend REMIXER_VISUAL_DEBUGGER_SIGNATURE_SKELETON()